name: Android UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install Appium
      run: |
        npm install -g appium@2.0.0
        npm install -g appium-uiautomator2-driver
    
    - name: Create AVD and start emulator
      run: |
        sdkmanager "system-images;android-30;google_apis;x86_64"
        echo "no" | avdmanager create avd -n test_avd -k "system-images;android-30;google_apis;x86_64"
        nohup $ANDROID_HOME/emulator/emulator -avd test_avd -no-audio -no-window &
        adb wait-for-device
    
    - name: Start Appium Server
      run: |
        appium --allow-insecure chromedriver_autodownload &
        sleep 10
    
    - name: Setup APK
      run: |
        mkdir -p app
        # Download APK from Google Drive using wget or curl
        wget -O app/your-app.apk "${{ secrets.APK_DOWNLOAD_URL }}" || \
        curl -L -o app/your-app.apk "${{ secrets.APK_DOWNLOAD_URL }}"
    
    - name: Run Tests
      run: |
        pytest tests/ -v 